# Generated by Django 4.2.7 on 2023-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office_visited', models.BooleanField(default=False)),
                ('contract_signed', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('sales_channel', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
